const state_list = [{ "code": "AN", "value": "Andaman and Nicobar Islands" },
{ "code": "AP", "value": "Andhra Pradesh" },
{ "code": "AR", "value": "Arunachal Pradesh" },
{ "code": "AS", "value": "Assam" },
{ "code": "BR", "value": "Bihar" },
{ "code": "CG", "value": "Chandigarh" },
{ "code": "CH", "value": "Chhattisgarh" },
{ "code": "DH", "value": "Dadra and Nagar Haveli" },
{ "code": "DD", "value": "Daman and Diu" },
{ "code": "DL", "value": "Delhi" },
{ "code": "GA", "value": "Goa" },
{ "code": "GJ", "value": "Gujarat" },
{ "code": "HR", "value": "Haryana" },
{ "code": "HP", "value": "Himachal Pradesh" },
{ "code": "JK", "value": "Jammu and Kashmir" },
{ "code": "JH", "value": "Jharkhand" },
{ "code": "KA", "value": "Karnataka" },
{ "code": "KL", "value": "Kerala" },
{ "code": "LD", "value": "Lakshadweep" },
{ "code": "MP", "value": "Madhya Pradesh" },
{ "code": "MH", "value": "Maharashtra" },
{ "code": "MN", "value": "Manipur" },
{ "code": "ML", "value": "Meghalaya" },
{ "code": "MZ", "value": "Mizoram" },
{ "code": "NL", "value": "Nagaland" },
{ "code": "OR", "value": "Odisha" },
{ "code": "PY", "value": "Puducherry" },
{ "code": "PB", "value": "Punjab" },
{ "code": "RJ", "value": "Rajasthan" },
{ "code": "SK", "value": "Sikkim" },
{ "code": "TN", "value": "Tamil Nadu" },
{ "code": "TS", "value": "Telangana" },
{ "code": "TR", "value": "Tripura" },
{ "code": "UK", "value": "Uttarakhand" },
{ "code": "UP", "value": "Uttar Pradesh" },
{ "code": "WB", "value": "West Bengal" }];

module.exports = state_list;