export const selum = [{label : 'A.Ayyamperumalpatti', value: '1'},
{label : 'Achanguttaipatti', value: '1'},
{label : 'Achanguttapattipudur', value: '1'},
{label : 'Adikarapatti', value: '1'},
{label : 'Adimalaipatti', value: '1'},
{label : 'Agraharapulaveri', value: '1'},
{label : 'Akkaraipalaiyam', value: '1'},
{label : 'Ammapalayam', value: '1'},
{label : 'Anaikuttaipatti', value: '1'},
{label : 'Andipatti-Sowdapuram', value: '1'},
{label : 'Arikkavandanpatti', value: '1'},
{label : 'Ariyampalayam', value: '1'},
{label : 'Attavanaipulaveri', value: '1'},
{label : 'Attayampatti (TP)', value: '1'},
{label : 'Basuvanathampatti', value: '1'},
{label : 'Chennagiri (CT)', value: '1'},
{label : 'Chettichavadi', value: '1'},
{label : 'Chinnasiragapadi', value: '1'},
{label : 'D.Perumalpalayam', value: '1'},
{label : 'Dalavaipatti (CT)', value: '1'},
{label : 'Dasanaickenpatti (CT)', value: '1'},
{label : 'Dasinayakkanpatti', value: '1'},
{label : 'Ellimanaickampatti', value: '1'},
{label : 'Errachinnampatti', value: '1'},
{label : 'Erumanayakanpalayam', value: '1'},
{label : 'Erumapalayam (CT)', value: '1'},
{label : 'Eruvadipettampatti', value: '1'},
{label : 'Gajallnayakkanpatti', value: '1'},
{label : 'Ilampillai (TP)', value: '1'},
{label : 'J.Veeranam', value: '1'},
{label : 'Jalluthuppatti', value: '1'},
{label : 'Jalluthuppatti R.F.', value: '1'},
{label : 'Jerugumalai', value: '1'},
{label : 'Jerugumalai R.F.', value: '1'},
{label : 'Kadathur Agraharam', value: '1'},
{label : 'Kalparapatti (CT)', value: '1'},
{label : 'Kammalapatti', value: '1'},
{label : 'Kanjamalai R.F.', value: '1'},
{label : 'Kannankurichi (TP)', value: '1'},
{label : 'Karichipatti', value: '1'},
{label : 'Kathiripatti', value: '1'},
{label : 'Keeraipappambadi', value: '1'},
{label : 'Konamaduvu', value: '1'},
{label : 'Kondalampatti (CT)', value: '1'},
{label : 'Kondappanaickenpatti (CT)', value: '1'},
{label : 'Korathupatti', value: '1'},
{label : 'kuralnatham', value: '1'},
{label : 'Luguvanpatti', value: '1'},
{label : 'M.Palapatti', value: '1'},
{label : 'Majaragollappatti (CT)', value: '1'},
{label : 'Mallamooppampatti (CT)', value: '1'},
{label : 'Mallaravuthampatti', value: '1'},
{label : 'Mallur (TP)', value: '1'},
{label : 'Maramangalathupatti (CT)', value: '1'},
{label : 'Marulayampalayam', value: '1'},
{label : 'Mettupattithathanur', value: '1'},
{label : 'Muduthurai', value: '1'},
{label : 'Mukkuthipalayam', value: '1'},
{label : 'Murungapatti', value: '1'},
{label : 'Nagarmalai R.F.', value: '1'},
{label : 'Nallampatti', value: '1'},
{label : 'Nallarayampatti', value: '1'},
{label : 'Nallikkalpatti', value: '1'},
{label : 'Nayakkanpatti', value: '1'},
{label : 'Neykkarappatti (CT)', value: '1'},
{label : 'Nilavarapatti (Part)', value: '1'},
{label : 'Nuleathukombai', value: '1'},
{label : 'Palampatti', value: '1'},
{label : 'Pallampatti', value: '1'},
{label : 'Pallipatti', value: '1'},
{label : 'Pallitherupatti', value: '1'},
{label : 'Panaimarathupatti (TP)', value: '1'},
{label : 'Papparapatti (CT)', value: '1'},
{label : 'Parappatti', value: '1'},
{label : 'Periyaseeragapadi', value: '1'},
{label : 'Perumagoundampatti (CT)', value: '1'},
{label : 'Perumampatti', value: '1'},
{label : 'Pumandapatti', value: '1'},
{label : 'Puthur Agraharam (CT)', value: '1'},
{label : 'Rajapalayam (CT)', value: '1'},
{label : 'Rakkipatti', value: '1'},
{label : 'Salem (M Corp.)', value: '1'},
{label : 'Sambakuttaipatti', value: '1'},
{label : 'Sandiyur Attayampatti', value: '1'},
{label : 'Sanniyasigundu (CT)', value: '1'},
{label : 'Sarkar Gollappatti', value: '1'},
{label : 'Selathampatti (CT)', value: '1'},
{label : 'Senaipalayam', value: '1'},
{label : 'Sittanur Gollapatti', value: '1'},
{label : 'Sukkampatti', value: '1'},
{label : 'Tailanur', value: '1'},
{label : 'Thammanayakkanpatti', value: '1'},
{label : 'Thumbalpatti', value: '1'},
{label : 'Thunbathulipatti', value: '1'},
{label : 'Tippampatti', value: '1'},
{label : 'Tirumalaigiri (CT)', value: '1'},
{label : 'Udayapatti', value: '1'},
{label : 'Uthamasolapuram', value: '1'},
{label : 'Valaiyakkaranur', value: '1'},
{label : 'Valakuttapatti', value: '1'},
{label : 'Valasaiyur', value: '1'},
{label : 'Vaniyampadi', value: '1'},
{label : 'Vattamuthampatti', value: '1'},
{label : 'Vedakuttampatti', value: '1'},
{label : 'Veerapandi', value: '1'},
{label : 'Vellaiyanpatti', value: '1'},
{label : 'Vembadithalam', value: '1'}]